#Step1: Build

FROM openjdk:11-jdk-slim AS java-build
COPY . .
RUN ./gradlew build

#Step2: Install
FROM openjdk:11-jre-slim
VOLUME /tmp
ARG JAR_FILE
COPY --from=java-build build/libs/mini-bank-0.0.1-SNAPSHOT.jar mini-bank-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/mini-bank-0.0.1-SNAPSHOT.jar"]
